// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxAV03oqvzdLh05yiJWT5AznquEja_TQ',
    appId: '1:857947979264:web:19c3cc274be2627a10e2e5',
    messagingSenderId: '857947979264',
    projectId: 'insta-clone0',
    authDomain: 'insta-clone0.firebaseapp.com',
    storageBucket: 'insta-clone0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOUzuj3dSgk5D1r2bCod60ggtSK0HISH0',
    appId: '1:857947979264:android:3543dc8eba011b9510e2e5',
    messagingSenderId: '857947979264',
    projectId: 'insta-clone0',
    storageBucket: 'insta-clone0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBkTluuWnmZJtv8oYI3iO2s7c6AgQlz9I',
    appId: '1:857947979264:ios:cb9a12c1af7b012410e2e5',
    messagingSenderId: '857947979264',
    projectId: 'insta-clone0',
    storageBucket: 'insta-clone0.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBkTluuWnmZJtv8oYI3iO2s7c6AgQlz9I',
    appId: '1:857947979264:ios:cb9a12c1af7b012410e2e5',
    messagingSenderId: '857947979264',
    projectId: 'insta-clone0',
    storageBucket: 'insta-clone0.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1j1gvjUvdyrsYnYvG0wNW5p_J8M2p3g',
    appId: '1:857947979264:web:a0d6de92461eb1f110e2e5',
    messagingSenderId: '857947979264',
    projectId: 'insta-clone0',
    authDomain: 'insta-clone0.firebaseapp.com',
    storageBucket: 'insta-clone0.appspot.com',
  );
}
